Jidea-151 Costs table
jameel-institute/daedalus-web-app pull request #59
Opened 2024-10-18 13:06 UTC by absternator

The following PR is for work for displaying the costs table as well as with the pie chart

![image](https://github.com/user-attachments/assets/421c0edd-e7fc-48ec-b7ed-c3bed804a94f)
![image](https://github.com/user-attachments/assets/b53a32e3-72ee-4f43-8f10-4ca8d7ce7ccf)

2024-10-21 07:59 UTC, david-mears-2 requested changes
Looks good :)

A couple of changes and discussion points.

2024-10-21 07:59 UTC, david-mears-2 commented on stores/appStore.ts
> +    },
I like that you've moved this to the store.

2024-10-21 07:59 UTC, david-mears-2 commented on tests/e2e/runAnalysis.spec.ts
> +    await expect(page.locator(".highcharts-background").first()).toHaveScreenshot("first-time-series.png", { maxDiffPixelRatio: 0.04, timeout: 15000 });
I think these changes to the e2e test appear here because the branch is out of date with the latest version of jidea-105-14-oct

2024-10-21 07:59 UTC, david-mears-2 commented on tests/unit/components/CostsCard.spec.ts
> -import { mockResizeObserver } from "jsdom-testing-mocks";
Could you also excise this from npm too please?

2024-10-21 07:59 UTC, david-mears-2 commented on tests/unit/components/CostsPie.spec.ts
> +      global: { stubs, plugins: [mockPinia({ metadata: mockedMetadata }, true, false)] },
You don't need to import and pass in the mockedMetadata -- mockPinia already does this by default (if you set  the second parameter to true)

2024-10-21 07:59 UTC, david-mears-2 commented on tests/unit/mocks/mockPinia.ts
> +  return createTestingPinia({ initialState, createSpy: vi.fn, stubActions });
Another open PR, #47, adds the ability to stub actions from pinia in a bit more of a generic way, allowing the user of mockPinia to pass in a *dict* of options that is forwarded to createTestingPinia. Please could you copy the way this is done in the relevant commit: https://github.com/jameel-institute/daedalus-web-app/pull/47/commits/ae8adb3c1d060ecfe2017fa5c6417a5a507492ef

2024-10-21 07:59 UTC, david-mears-2 commented on components/CostsTable.vue
> +</style>
```suggestion
<style scoped>
.nested-row {
  background-color: #f1f3f5;
}

td {
  padding-left: 0.5rem;
}
</style>
```

This looks a little neater to me on hover.

2024-10-21 11:02 UTC, david-mears-2 commented on tests/unit/mocks/mockPinia.ts
> +  return createTestingPinia({ initialState, createSpy: vi.fn, stubActions });
Though actually (as I'm fixing elsewhere) I think the parameter
```ts
  testingOpts: TestingOptions = {},
```
should be
```ts
  testingOpts: Partial<TestingOptions> = {},
```

2024-10-21 12:42 UTC, absternator commented on components/CostsTable.vue
> +        <th>Total in M$</th>
yeah thought it was a bit confusing... but the usual table format for currency usually just numbers and can't use abbreviated as it differs and seems odd in a table..... I've changed to heading to **$ in millions** as that seems better

2024-10-21 12:46 UTC, absternator commented on components/CostsTable.vue
> +        <th>Loss</th>
ive removed first column header and second column is as change above ($ in millions)...

2024-10-22 08:20 UTC, david-mears-2 commented
A suggestion I liked from the scientists: omit the dollar sign on each row and just have it in the column header. This prevents confusion if your eye goes directly to the row without reading the unit in the column header.

2024-10-22 12:10 UTC, david-mears-2 commented
For some reason, now this branch uses the costs pie colours in a different order than before (see screenshots). I prefer blue to be the color Highcharts tends to apply to the Life years segment, since that's almost always the largest.
![Screenshot from 2024-10-22 13-08-56](https://github.com/user-attachments/assets/823b07a6-8506-4757-a522-53da994088c2)
![Screenshot from 2024-10-22 13-09-20](https://github.com/user-attachments/assets/8687bf3f-4187-463d-a01b-d682c809f48b)

2024-10-22 12:26 UTC, david-mears-2 reviewed
See comment just now - Could you please try to work out what's causing the costs pie colours to change? The originals won't be the final colours but it would be really good if we were in complete control of the colours, so we need to understand how it was affected.

2024-10-22 12:26 UTC, david-mears-2 commented on components/CostsTable.vue
> +        <th>$ in millions</th>
```suggestion
        <th>$, millions</th>
```

2024-10-22 12:26 UTC, david-mears-2 commented on components/CostsTable.vue
> +            class="nested-row"
```suggestion
            class="nested-row fw-lighter"
```

2024-10-22 12:26 UTC, david-mears-2 commented on components/CostsTable.vue
> +</style>
I think this suggestion failed to make it in. Also, a mild change to the font weight of the thead:

```suggestion
<style scoped>
.nested-row {
  background-color: #f1f3f5;
}

td {
  padding-left: 0.5rem;
}

thead tr th {
  font-weight: 600 !important;
}
</style>
```

2024-10-23 16:52 UTC, david-mears-2 approved these changes
Thanks so much @absternator, I'm happy with this pending Emma's once-over.

2024-10-24 09:13 UTC, EmmaLRussell approved these changes
This looks great!

It looks a little bit odd, having some values presented as B or T USD, others as 100s of M USD, and VSL in Int'l$. But we're going to tidy that up post-workshop I think.

2024-10-24 11:01 UTC, merged